-- ==========================================
-- TABLES & CONSTRAINTS
-- ==========================================

CREATE TABLE "ACC_ASIGNACIONES" 
   (	"ID_ASIGNACION" NUMBER, 
	"ID_PADRE" NUMBER, 
	"ID_HIJO" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_ASOCIACIONES" 
   (	"ID_ASOCIACION" NUMBER, 
	"ID_USR_ATTR" NUMBER, 
	"ID_OBJ_ATTR" NUMBER, 
	"ID_OP" NUMBER, 
	"CONDICION_JSON" VARCHAR2(2000 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_LOG_ACCESOS" 
   (	"ID_LOG" NUMBER, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"CODIGO_OBJETO" VARCHAR2(100 BYTE), 
	"OPERACIONES" VARCHAR2(256 BYTE), 
	"AUTORIZADO" NUMBER(1,0), 
	"JSON_CONTEXTO" CLOB, 
	"FECHA_REGISTRO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   );

CREATE TABLE "ACC_LOG_ERRORES" 
   (	"ID_LOG" NUMBER, 
	"FECHA" DATE DEFAULT SYSDATE, 
	"MODULO" VARCHAR2(100 BYTE), 
	"MENSAJE" VARCHAR2(4000 BYTE)
   );

CREATE TABLE "ACC_MENU_ASIGNACIONES" 
   (	"ID_MENU_ASIGNACION" NUMBER, 
	"ID_MENU_PADRE" NUMBER, 
	"ID_MENU_HIJO" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_MENU_NODOS" 
   (	"ID_MENU_NODO" NUMBER, 
	"ID_NODO" NUMBER, 
	"ETIQUETA_VISIBLE" VARCHAR2(500 BYTE), 
	"URL_RUTA_VISIBLE" VARCHAR2(1000 BYTE), 
	"SLUG_VISIBLE" VARCHAR2(500 BYTE), 
	"ICONO_VISIBLE" VARCHAR2(100 BYTE), 
	"DESCRIPCION_VISIBLE" VARCHAR2(1000 BYTE), 
	"ORDEN_VISUAL" NUMBER DEFAULT 0, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_NODOS" 
   (	"ID_NODO" NUMBER, 
	"ID_TIPO_NODO" NUMBER, 
	"CODIGO_TECNICO" VARCHAR2(255 BYTE), 
	"ETIQUETA" VARCHAR2(500 BYTE), 
	"URL_RUTA" VARCHAR2(1000 BYTE), 
	"SLUG" VARCHAR2(500 BYTE), 
	"ICONO" VARCHAR2(100 BYTE), 
	"ORDEN_VISUAL" NUMBER DEFAULT 0, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_OPERACIONES" 
   (	"ID_OP" NUMBER, 
	"NOMBRE_OP" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_POLICY_MENU_RAICES" 
   (	"ID_POLICY_MENU_RAIZ" NUMBER, 
	"ID_POLICY" NUMBER, 
	"ID_MENU_NODO" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_PROHIBICIONES" 
   (	"ID_PROHIBICION" NUMBER, 
	"ID_USR_ATTR" NUMBER, 
	"ID_OBJ_ATTR" NUMBER, 
	"ID_OP" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_ROLES" 
   (	"ID_ROL" NUMBER, 
	"CODIGO" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "ACC_TIPOS_NODO" 
   (	"ID_TIPO_NODO" NUMBER, 
	"CODIGO_TIPO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_ENTIDADES" 
   (	"ID_ENTIDAD" NUMBER, 
	"SLUG_ENTIDAD" VARCHAR2(4000 BYTE), 
	"NOMBRE_ENTIDAD" VARCHAR2(255 BYTE), 
	"TIPO_ENTIDAD" VARCHAR2(50 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"CODIGO" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_MODULO_NODOS" 
   (	"ID_MODULO_NODO" NUMBER, 
	"ID_MODULO" NUMBER, 
	"ID_NODO" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_MODULOS" 
   (	"ID_MODULO" NUMBER, 
	"CODIGO" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"FECHA_CREACION" DATE DEFAULT SYSDATE, 
	"CREADO_POR" VARCHAR2(100 BYTE) DEFAULT USER, 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_UNIDADES" 
   (	"ID_UNIDAD" NUMBER, 
	"SLUG_UNIDAD" VARCHAR2(4000 BYTE), 
	"NOMBRE_UNIDAD" VARCHAR2(255 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE) DEFAULT 'S', 
	"CODIGO" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_UNIDADES_ENTIDADES" 
   (	"ID_UNIDAD" NUMBER, 
	"ID_ENTIDAD" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_USUARIOS" 
   (	"ID_USUARIO" NUMBER, 
	"SLUG_USUARIO" VARCHAR2(100 BYTE), 
	"RUT" NUMBER, 
	"DV" VARCHAR2(1 BYTE), 
	"NOMBRES" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(150 BYTE), 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_USUARIOS_ENTIDADES" 
   (	"ID_USUARIO" NUMBER, 
	"ID_ENTIDAD" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

CREATE TABLE "SAFI_USUARIOS_UNIDADES" 
   (	"ID_USUARIO" NUMBER, 
	"ID_UNIDAD" NUMBER, 
	"ACTIVO" VARCHAR2(1 BYTE), 
	"FECHA_CREACION" DATE, 
	"CREADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"MODIFICADO_POR" VARCHAR2(100 BYTE), 
	"FECHA_ELIMINACION" DATE, 
	"ELIMINADO_POR" VARCHAR2(100 BYTE)
   );

-- Constraints

ALTER TABLE "ACC_ASIGNACIONES" ADD CONSTRAINT "PK_ACC_ASIGNACIONES" PRIMARY KEY ("ID_ASIGNACION")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_ASIGNACIONES" ADD CONSTRAINT "UQ_ACC_ASIGN_REL" UNIQUE ("ID_PADRE", "ID_HIJO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_ASOCIACIONES" ADD CONSTRAINT "PK_ACC_ASOCIACIONES" PRIMARY KEY ("ID_ASOCIACION")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_ASOCIACIONES" ADD CONSTRAINT "UQ_ACC_ASOC_REL" UNIQUE ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_LOG_ACCESOS" ADD CONSTRAINT "PK_ACC_LOG_ACCESOS" PRIMARY KEY ("ID_LOG")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_MENU_ASIGNACIONES" ADD CONSTRAINT "CHK_ACC_MENU_ASIG_ACTIVO" CHECK (activo IN ('S','N')) ENABLE;

ALTER TABLE "ACC_MENU_ASIGNACIONES" ADD CONSTRAINT "PK_ACC_MENU_ASIGNACIONES" PRIMARY KEY ("ID_MENU_ASIGNACION")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_MENU_ASIGNACIONES" ADD CONSTRAINT "UQ_ACC_MENU_ASIG_REL" UNIQUE ("ID_MENU_PADRE", "ID_MENU_HIJO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_MENU_NODOS" ADD CONSTRAINT "CHK_ACC_MENU_NODOS_ACTIVO" CHECK (activo IN ('S','N')) ENABLE;

ALTER TABLE "ACC_MENU_NODOS" ADD CONSTRAINT "PK_ACC_MENU_NODOS" PRIMARY KEY ("ID_MENU_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_NODOS" ADD CONSTRAINT "CHK_ACC_NODOS_ACTIVO" CHECK (activo IN ('S', 'N')) ENABLE;

ALTER TABLE "ACC_NODOS" ADD CONSTRAINT "PK_ACC_NODOS" PRIMARY KEY ("ID_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_NODOS" ADD CONSTRAINT "UQ_ACC_NODOS_COD" UNIQUE ("CODIGO_TECNICO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_OPERACIONES" ADD CONSTRAINT "PK_ACC_OPERACIONES" PRIMARY KEY ("ID_OP")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_OPERACIONES" ADD CONSTRAINT "UQ_ACC_OPERACIONES_NOM" UNIQUE ("NOMBRE_OP")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_POLICY_MENU_RAICES" ADD CONSTRAINT "CHK_ACC_POL_MENU_ACTIVO" CHECK (activo IN ('S','N')) ENABLE;

ALTER TABLE "ACC_POLICY_MENU_RAICES" ADD CONSTRAINT "PK_ACC_POLICY_MENU_RAICES" PRIMARY KEY ("ID_POLICY_MENU_RAIZ")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_POLICY_MENU_RAICES" ADD CONSTRAINT "UQ_ACC_POL_MENU_REL" UNIQUE ("ID_POLICY", "ID_MENU_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_PROHIBICIONES" ADD CONSTRAINT "PK_ACC_PROHIBICIONES" PRIMARY KEY ("ID_PROHIBICION")
  USING INDEX COMPUTE STATISTICS 
    ENABLE;

ALTER TABLE "ACC_PROHIBICIONES" ADD CONSTRAINT "UQ_ACC_PROH_REL" UNIQUE ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP")
  USING INDEX COMPUTE STATISTICS 
    ENABLE;

ALTER TABLE "ACC_ROLES" ADD CONSTRAINT "PK_ACC_ROLES" PRIMARY KEY ("ID_ROL")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_ROLES" ADD CONSTRAINT "UQ_ACC_ROLES" UNIQUE ("CODIGO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_TIPOS_NODO" ADD CONSTRAINT "PK_ACC_TIPOS_NODO" PRIMARY KEY ("ID_TIPO_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "ACC_TIPOS_NODO" ADD CONSTRAINT "UQ_ACC_TIPOS_CODIGO" UNIQUE ("CODIGO_TIPO")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_MODULO_NODOS" ADD CONSTRAINT "SAFI_MODULO_NODOS_PK" PRIMARY KEY ("ID_MODULO_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_MODULO_NODOS" ADD CONSTRAINT "SAFI_MODULO_NODOS_UK" UNIQUE ("ID_MODULO", "ID_NODO")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_MODULOS" ADD CONSTRAINT "SAFI_MODULOS_PK" PRIMARY KEY ("ID_MODULO")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_MODULOS" ADD CONSTRAINT "SAFI_MODULOS_CODIGO_UK" UNIQUE ("CODIGO")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_UNIDADES_ENTIDADES" ADD CONSTRAINT "PK_SAFI_UNI_ENT" PRIMARY KEY ("ID_UNIDAD", "ID_ENTIDAD")
  USING INDEX COMPUTE STATISTICS 
    ENABLE;

ALTER TABLE "SAFI_USUARIOS_ENTIDADES" ADD CONSTRAINT "PK_SAFI_USU_ENT" PRIMARY KEY ("ID_USUARIO", "ID_ENTIDAD")
  USING INDEX 
    ENABLE;

ALTER TABLE "SAFI_USUARIOS_UNIDADES" ADD CONSTRAINT "PK_SAFI_USU_UNI" PRIMARY KEY ("ID_USUARIO", "ID_UNIDAD")
  USING INDEX COMPUTE STATISTICS 
    ENABLE;

ALTER TABLE "ACC_ASIGNACIONES" ADD CONSTRAINT "FK_ASIG_PADRE" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ON DELETE CASCADE ENABLE;

ALTER TABLE "ACC_ASIGNACIONES" ADD CONSTRAINT "FK_ASIG_HIJO" FOREIGN KEY ("ID_HIJO")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ON DELETE CASCADE ENABLE;

ALTER TABLE "ACC_ASOCIACIONES" ADD CONSTRAINT "FK_ASOC_USR" FOREIGN KEY ("ID_USR_ATTR")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_ASOCIACIONES" ADD CONSTRAINT "FK_ASOC_OBJ" FOREIGN KEY ("ID_OBJ_ATTR")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_ASOCIACIONES" ADD CONSTRAINT "FK_ASOC_OP" FOREIGN KEY ("ID_OP")
	  REFERENCES "ACC_OPERACIONES" ("ID_OP") ENABLE;

ALTER TABLE "ACC_MENU_ASIGNACIONES" ADD CONSTRAINT "FK_ACC_MENU_ASIG_PADRE" FOREIGN KEY ("ID_MENU_PADRE")
	  REFERENCES "ACC_MENU_NODOS" ("ID_MENU_NODO") ENABLE;

ALTER TABLE "ACC_MENU_ASIGNACIONES" ADD CONSTRAINT "FK_ACC_MENU_ASIG_HIJO" FOREIGN KEY ("ID_MENU_HIJO")
	  REFERENCES "ACC_MENU_NODOS" ("ID_MENU_NODO") ENABLE;

ALTER TABLE "ACC_MENU_NODOS" ADD CONSTRAINT "FK_ACC_MENU_NODO" FOREIGN KEY ("ID_NODO")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_NODOS" ADD CONSTRAINT "FK_NODO_TIPO" FOREIGN KEY ("ID_TIPO_NODO")
	  REFERENCES "ACC_TIPOS_NODO" ("ID_TIPO_NODO") ENABLE;

ALTER TABLE "ACC_POLICY_MENU_RAICES" ADD CONSTRAINT "FK_ACC_POL_MENU_POLICY" FOREIGN KEY ("ID_POLICY")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_POLICY_MENU_RAICES" ADD CONSTRAINT "FK_ACC_POL_MENU_RAIZ" FOREIGN KEY ("ID_MENU_NODO")
	  REFERENCES "ACC_MENU_NODOS" ("ID_MENU_NODO") ENABLE;

ALTER TABLE "ACC_PROHIBICIONES" ADD CONSTRAINT "FK_PROH_USR" FOREIGN KEY ("ID_USR_ATTR")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_PROHIBICIONES" ADD CONSTRAINT "FK_PROH_OBJ" FOREIGN KEY ("ID_OBJ_ATTR")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "ACC_PROHIBICIONES" ADD CONSTRAINT "FK_PROH_OP" FOREIGN KEY ("ID_OP")
	  REFERENCES "ACC_OPERACIONES" ("ID_OP") ENABLE;

ALTER TABLE "SAFI_MODULO_NODOS" ADD CONSTRAINT "SAFI_MODULO_NODOS_MODULO_FK" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "SAFI_MODULOS" ("ID_MODULO") ENABLE;

ALTER TABLE "SAFI_MODULO_NODOS" ADD CONSTRAINT "SAFI_MODULO_NODOS_NODO_FK" FOREIGN KEY ("ID_NODO")
	  REFERENCES "ACC_NODOS" ("ID_NODO") ENABLE;

ALTER TABLE "SAFI_UNIDADES_ENTIDADES" ADD CONSTRAINT "FK_SAFI_UNI_ENT_UNI" FOREIGN KEY ("ID_UNIDAD")
	  REFERENCES "SAFI_UNIDADES" ("ID_UNIDAD") ON DELETE CASCADE ENABLE;

ALTER TABLE "SAFI_UNIDADES_ENTIDADES" ADD CONSTRAINT "FK_SAFI_UNI_ENT_ENT" FOREIGN KEY ("ID_ENTIDAD")
	  REFERENCES "SAFI_ENTIDADES" ("ID_ENTIDAD") ON DELETE CASCADE ENABLE;

ALTER TABLE "SAFI_USUARIOS_ENTIDADES" ADD CONSTRAINT "FK_SAFI_USU_ENT_ENT" FOREIGN KEY ("ID_ENTIDAD")
	  REFERENCES "SAFI_ENTIDADES" ("ID_ENTIDAD") ON DELETE CASCADE ENABLE;

ALTER TABLE "SAFI_USUARIOS_UNIDADES" ADD CONSTRAINT "FK_SAFI_USU_UNI_UNI" FOREIGN KEY ("ID_UNIDAD")
	  REFERENCES "SAFI_UNIDADES" ("ID_UNIDAD") ON DELETE CASCADE ENABLE;
