-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX "IDX_ACC_MENU_ASIG_HIJO" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_HIJO") 
   ;

CREATE INDEX "IDX_ACC_MENU_ASIG_PADRE" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_PADRE") 
   ;

CREATE INDEX "IDX_ACC_MENU_NODOS_NODO" ON "ACC_MENU_NODOS" ("ID_NODO") 
   ;

CREATE INDEX "IDX_ACC_POL_MENU_POLICY" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY") 
   ;

CREATE INDEX "IDX_ACC_POL_MENU_RAIZ" ON "ACC_POLICY_MENU_RAICES" ("ID_MENU_NODO") 
   ;

CREATE INDEX "IDX_ASIG_HIJO" ON "ACC_ASIGNACIONES" ("ID_HIJO", "ID_PADRE") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_OBJ" ON "ACC_ASOCIACIONES" ("ID_OBJ_ATTR") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_OP" ON "ACC_ASOCIACIONES" ("ID_OP") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_USR" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_USR_OBJ" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_FECHA" ON "ACC_LOG_ACCESOS" ("FECHA_REGISTRO") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_OBJ" ON "ACC_LOG_ACCESOS" ("CODIGO_OBJETO") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_USR" ON "ACC_LOG_ACCESOS" ("USUARIO") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_FECHA" ON "ACC_LOG_ERRORES" ("FECHA") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_FECHA_MODULO" ON "ACC_LOG_ERRORES" ("FECHA", "MODULO") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_MODULO" ON "ACC_LOG_ERRORES" ("MODULO") 
   ;

CREATE INDEX "IDX_NODOS_TIPO" ON "ACC_NODOS" ("ID_TIPO_NODO", "ACTIVO") 
   ;

CREATE INDEX "IDX_SAFI_UNIENT_ENT" ON "SAFI_UNIDADES_ENTIDADES" ("ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_UNIENT_UNI" ON "SAFI_UNIDADES_ENTIDADES" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_USUENT_ENT" ON "SAFI_USUARIOS_ENTIDADES" ("ID_ENTIDAD") 
   ;

CREATE INDEX "IDX_SAFI_USUENT_USU" ON "SAFI_USUARIOS_ENTIDADES" ("ID_USUARIO") 
   ;

CREATE INDEX "IDX_SAFI_USUUNI_UNI" ON "SAFI_USUARIOS_UNIDADES" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_USUUNI_USU" ON "SAFI_USUARIOS_UNIDADES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "PK_ACC_ASIGNACIONES" ON "ACC_ASIGNACIONES" ("ID_ASIGNACION") 
   ;

CREATE UNIQUE INDEX "PK_ACC_ASOCIACIONES" ON "ACC_ASOCIACIONES" ("ID_ASOCIACION") 
   ;

CREATE UNIQUE INDEX "PK_ACC_LOG_ACCESOS" ON "ACC_LOG_ACCESOS" ("ID_LOG") 
   ;

CREATE UNIQUE INDEX "PK_ACC_MENU_ASIGNACIONES" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_ASIGNACION") 
   ;

CREATE UNIQUE INDEX "PK_ACC_MENU_NODOS" ON "ACC_MENU_NODOS" ("ID_MENU_NODO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_NODOS" ON "ACC_NODOS" ("ID_NODO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_OPERACIONES" ON "ACC_OPERACIONES" ("ID_OP") 
   ;

CREATE UNIQUE INDEX "PK_ACC_POLICY_MENU_RAICES" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY_MENU_RAIZ") 
   ;

CREATE UNIQUE INDEX "PK_ACC_PROHIBICIONES" ON "ACC_PROHIBICIONES" ("ID_PROHIBICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "PK_ACC_ROLES" ON "ACC_ROLES" ("ID_ROL") 
   ;

CREATE UNIQUE INDEX "PK_ACC_TIPOS_NODO" ON "ACC_TIPOS_NODO" ("ID_TIPO_NODO") 
   ;

CREATE UNIQUE INDEX "PK_SAFI_UNI_ENT" ON "SAFI_UNIDADES_ENTIDADES" ("ID_UNIDAD", "ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "PK_SAFI_USU_ENT" ON "SAFI_USUARIOS_ENTIDADES" ("ID_USUARIO", "ID_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "PK_SAFI_USU_UNI" ON "SAFI_USUARIOS_UNIDADES" ("ID_USUARIO", "ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "SAFI_MODULO_NODOS_PK" ON "SAFI_MODULO_NODOS" ("ID_MODULO_NODO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULO_NODOS_UK" ON "SAFI_MODULO_NODOS" ("ID_MODULO", "ID_NODO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULOS_CODIGO_UK" ON "SAFI_MODULOS" ("CODIGO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULOS_PK" ON "SAFI_MODULOS" ("ID_MODULO") 
   ;

CREATE UNIQUE INDEX "SYS_C008582" ON "ACC_LOG_ERRORES" ("ID_LOG") 
   ;

CREATE UNIQUE INDEX "SYS_C008630" ON "SAFI_USUARIOS" ("SLUG_USUARIO") 
   ;

CREATE UNIQUE INDEX "SYS_C008631" ON "SAFI_USUARIOS" ("RUT") 
   ;

CREATE UNIQUE INDEX "SYS_C008635" ON "SAFI_UNIDADES" ("ID_UNIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008636" ON "SAFI_UNIDADES" ("SLUG_UNIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008640" ON "SAFI_ENTIDADES" ("ID_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008641" ON "SAFI_ENTIDADES" ("SLUG_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008699" ON "SAFI_USUARIOS" ("ID_USUARIO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ASIGN_REL" ON "ACC_ASIGNACIONES" ("ID_PADRE", "ID_HIJO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ASOC_REL" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_MENU_ASIG_REL" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_PADRE", "ID_MENU_HIJO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_NODOS_COD" ON "ACC_NODOS" ("CODIGO_TECNICO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_OPERACIONES_NOM" ON "ACC_OPERACIONES" ("NOMBRE_OP") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_POL_MENU_REL" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY", "ID_MENU_NODO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_PROH_REL" ON "ACC_PROHIBICIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ROLES" ON "ACC_ROLES" ("CODIGO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_TIPOS_CODIGO" ON "ACC_TIPOS_NODO" ("CODIGO_TIPO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_ASIGNACIONES" ON "ACC_ASIGNACIONES" ("ID_ASIGNACION") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ASIGN_REL" ON "ACC_ASIGNACIONES" ("ID_PADRE", "ID_HIJO") 
   ;

CREATE INDEX "IDX_ASIG_HIJO" ON "ACC_ASIGNACIONES" ("ID_HIJO", "ID_PADRE") 
   ;

CREATE UNIQUE INDEX "PK_ACC_ASOCIACIONES" ON "ACC_ASOCIACIONES" ("ID_ASOCIACION") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ASOC_REL" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_USR" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_OBJ" ON "ACC_ASOCIACIONES" ("ID_OBJ_ATTR") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_OP" ON "ACC_ASOCIACIONES" ("ID_OP") 
   ;

CREATE INDEX "IDX_ASOCIACIONES_USR_OBJ" ON "ACC_ASOCIACIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR") 
   ;

CREATE UNIQUE INDEX "PK_ACC_LOG_ACCESOS" ON "ACC_LOG_ACCESOS" ("ID_LOG") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_USR" ON "ACC_LOG_ACCESOS" ("USUARIO") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_FECHA" ON "ACC_LOG_ACCESOS" ("FECHA_REGISTRO") 
   ;

CREATE INDEX "IDX_LOG_ACCESOS_OBJ" ON "ACC_LOG_ACCESOS" ("CODIGO_OBJETO") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_MODULO" ON "ACC_LOG_ERRORES" ("MODULO") 
   ;

CREATE UNIQUE INDEX "SYS_C008582" ON "ACC_LOG_ERRORES" ("ID_LOG") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_FECHA" ON "ACC_LOG_ERRORES" ("FECHA") 
   ;

CREATE INDEX "IDX_LOG_ERRORES_FECHA_MODULO" ON "ACC_LOG_ERRORES" ("FECHA", "MODULO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_MENU_ASIGNACIONES" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_ASIGNACION") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_MENU_ASIG_REL" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_PADRE", "ID_MENU_HIJO") 
   ;

CREATE INDEX "IDX_ACC_MENU_ASIG_PADRE" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_PADRE") 
   ;

CREATE INDEX "IDX_ACC_MENU_ASIG_HIJO" ON "ACC_MENU_ASIGNACIONES" ("ID_MENU_HIJO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_MENU_NODOS" ON "ACC_MENU_NODOS" ("ID_MENU_NODO") 
   ;

CREATE INDEX "IDX_ACC_MENU_NODOS_NODO" ON "ACC_MENU_NODOS" ("ID_NODO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_NODOS" ON "ACC_NODOS" ("ID_NODO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_NODOS_COD" ON "ACC_NODOS" ("CODIGO_TECNICO") 
   ;

CREATE INDEX "IDX_NODOS_TIPO" ON "ACC_NODOS" ("ID_TIPO_NODO", "ACTIVO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_OPERACIONES" ON "ACC_OPERACIONES" ("ID_OP") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_OPERACIONES_NOM" ON "ACC_OPERACIONES" ("NOMBRE_OP") 
   ;

CREATE UNIQUE INDEX "PK_ACC_POLICY_MENU_RAICES" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY_MENU_RAIZ") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_POL_MENU_REL" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY", "ID_MENU_NODO") 
   ;

CREATE INDEX "IDX_ACC_POL_MENU_POLICY" ON "ACC_POLICY_MENU_RAICES" ("ID_POLICY") 
   ;

CREATE INDEX "IDX_ACC_POL_MENU_RAIZ" ON "ACC_POLICY_MENU_RAICES" ("ID_MENU_NODO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_PROHIBICIONES" ON "ACC_PROHIBICIONES" ("ID_PROHIBICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "UQ_ACC_PROH_REL" ON "ACC_PROHIBICIONES" ("ID_USR_ATTR", "ID_OBJ_ATTR", "ID_OP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "PK_ACC_ROLES" ON "ACC_ROLES" ("ID_ROL") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_ROLES" ON "ACC_ROLES" ("CODIGO") 
   ;

CREATE UNIQUE INDEX "PK_ACC_TIPOS_NODO" ON "ACC_TIPOS_NODO" ("ID_TIPO_NODO") 
   ;

CREATE UNIQUE INDEX "UQ_ACC_TIPOS_CODIGO" ON "ACC_TIPOS_NODO" ("CODIGO_TIPO") 
   ;

CREATE UNIQUE INDEX "SYS_C008640" ON "SAFI_ENTIDADES" ("ID_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008641" ON "SAFI_ENTIDADES" ("SLUG_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULO_NODOS_PK" ON "SAFI_MODULO_NODOS" ("ID_MODULO_NODO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULO_NODOS_UK" ON "SAFI_MODULO_NODOS" ("ID_MODULO", "ID_NODO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULOS_PK" ON "SAFI_MODULOS" ("ID_MODULO") 
   ;

CREATE UNIQUE INDEX "SAFI_MODULOS_CODIGO_UK" ON "SAFI_MODULOS" ("CODIGO") 
   ;

CREATE UNIQUE INDEX "SYS_C008635" ON "SAFI_UNIDADES" ("ID_UNIDAD") 
   ;

CREATE UNIQUE INDEX "SYS_C008636" ON "SAFI_UNIDADES" ("SLUG_UNIDAD") 
   ;

CREATE UNIQUE INDEX "PK_SAFI_UNI_ENT" ON "SAFI_UNIDADES_ENTIDADES" ("ID_UNIDAD", "ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_UNIENT_UNI" ON "SAFI_UNIDADES_ENTIDADES" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_UNIENT_ENT" ON "SAFI_UNIDADES_ENTIDADES" ("ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE UNIQUE INDEX "SYS_C008699" ON "SAFI_USUARIOS" ("ID_USUARIO") 
   ;

CREATE UNIQUE INDEX "SYS_C008630" ON "SAFI_USUARIOS" ("SLUG_USUARIO") 
   ;

CREATE UNIQUE INDEX "SYS_C008631" ON "SAFI_USUARIOS" ("RUT") 
   ;

CREATE UNIQUE INDEX "PK_SAFI_USU_ENT" ON "SAFI_USUARIOS_ENTIDADES" ("ID_USUARIO", "ID_ENTIDAD") 
   ;

CREATE INDEX "IDX_SAFI_USUENT_USU" ON "SAFI_USUARIOS_ENTIDADES" ("ID_USUARIO") 
   ;

CREATE INDEX "IDX_SAFI_USUENT_ENT" ON "SAFI_USUARIOS_ENTIDADES" ("ID_ENTIDAD") 
   ;

CREATE UNIQUE INDEX "PK_SAFI_USU_UNI" ON "SAFI_USUARIOS_UNIDADES" ("ID_USUARIO", "ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_USUUNI_USU" ON "SAFI_USUARIOS_UNIDADES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE INDEX "IDX_SAFI_USUUNI_UNI" ON "SAFI_USUARIOS_UNIDADES" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;
