BEGIN
    pkg_seguridad_admin.p_upsert_nodo('CAJA', 'Caja', 'OBJETO', '/caja', 'caja', 'point_of_sale', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PARAMETROS', 'Parámetros', 'OBJETO', '/caja/parametros', 'parametros', 'settings', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS', 'Procesos', 'OBJETO', '/caja/procesos', 'procesos', 'account_tree', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS', 'Consultas', 'OBJETO', '/caja/consultas', 'consultas', 'manage_search', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES', 'Informes', 'OBJETO', '/caja/informes', 'informes', 'assessment', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PARAMETROS_MANTENCION_UNIDAD', 'Mantención De Unidad', 'OBJETO', '/caja/parametros/mantencion-unidad', 'mantencion-de-unidad', 'domain', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PARAMETROS_MANTENCION_CAJA_RECAUDADORA', 'Mantencion Caja Recaudadora', 'OBJETO', '/caja/parametros/mantencion-caja-recaudadora', 'mantencion-caja-recaudadora', 'point_of_sale', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PARAMETROS_MANTENCION_CAJA_FUERTE', 'Mantencion Caja Fuerte', 'OBJETO', '/caja/parametros/mantencion-caja-fuerte', 'mantencion-caja-fuerte', 'lock', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PARAMETROS_MANTENCION_TIPO_DOCUMENTO', 'Mantencion Tipo Documento', 'OBJETO', '/caja/parametros/mantencion-tipo-documento', 'mantencion-tipo-documento', 'description', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION', 'Recaudación', 'OBJETO', '/caja/procesos/recaudacion', 'recaudacion', 'monetization_on', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_COMPROBANTE_EGRESO', 'Comprobante De Egreso', 'OBJETO', '/caja/procesos/recaudacion/comprobante-egreso', 'comprobante-de-egreso', 'money_off', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_ANULA_COMPROBANTE_INGRESO', 'Anula Comprobante De Ingreso', 'OBJETO', '/caja/procesos/recaudacion/anula-comprobante-ingreso', 'anula-comprobante-de-ingreso', 'cancel_presentation', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_COMPROBANTE_INGRESO_VENTAS_CREDITO', 'Comprobante De Ingreso Ventas Credito', 'OBJETO', '/caja/procesos/recaudacion/comprobante-ingreso-ventas-credito', 'comprobante-de-ingreso-ventas-credito', 'credit_score', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_ENTREGA_VALORES_DEPOSITO', 'Entrega Valores A Deposito', 'OBJETO', '/caja/procesos/recaudacion/entrega-valores-deposito', 'entrega-valores-a-deposito', 'local_shipping', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_RECEPCION_COMPROBANTE_DEPOSITO', 'Recepcion Comprobante De Deposito', 'OBJETO', '/caja/procesos/recaudacion/recepcion-comprobante-deposito', 'recepcion-comprobante-de-deposito', 'receipt_long', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_PROCESAR_ARQUEO_DIARIO', 'Procesar Arqueo Diario', 'OBJETO', '/caja/procesos/recaudacion/procesar-arqueo-diario', 'procesar-arqueo-diario', 'calculate', 6);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_ANULA_COMPROBANTE_INGRESO_VENTAS_CREDITO', 'Anula Comprobante De Ingreso Ventas Credito', 'OBJETO', '/caja/procesos/recaudacion/anula-comprobante-ingreso-ventas-credito', 'anula-comprobante-de-ingreso-ventas-credito', 'credit_card_off', 7);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_RECAUDACION_CORRECION_ARQUEO', 'Correcion De Arqueo', 'OBJETO', '/caja/procesos/recaudacion/correcion-arqueo', 'correcion-de-arqueo', 'edit_document', 8);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_PAGOS', 'Pagos', 'OBJETO', '/caja/procesos/pagos', 'pagos', 'payments', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_PAGOS_RECEPCION_ENTREGA_CHEQUES', 'Recepcion Y/O Entrega De Cheques', 'OBJETO', '/caja/procesos/pagos/recepcion-entrega-cheques', 'recepcion-y-o-entrega-de-cheques', 'swap_horiz', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_PAGOS_PODER_SIMPLE_RETIRO_CHEQUES', 'Poder Simple Retiro De Cheques', 'OBJETO', '/caja/procesos/pagos/poder-simple-retiro-cheques', 'poder-simple-retiro-de-cheques', 'assignment_ind', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA', 'Custodia', 'OBJETO', '/caja/procesos/custodia', 'custodia', 'security', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_INGRESO_CHEQUES_FECHA', 'Ingreso De Cheques A Fecha', 'OBJETO', '/caja/procesos/custodia/ingreso-cheques-fecha', 'ingreso-de-cheques-a-fecha', 'event_available', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_INGRESO_POLIZA_ESCUELAS_MATRICES', 'Ingreso De Poliza Escuelas Matrices', 'OBJETO', '/caja/procesos/custodia/ingreso-poliza-escuelas-matrices', 'ingreso-de-poliza-escuelas-matrices', 'policy', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_INGRESO_OTROS_DOCMENTOS', 'Ingreso De Otros Docmentos', 'OBJETO', '/caja/procesos/custodia/ingreso-otros-docmentos', 'ingreso-de-otros-docmentos', 'note_add', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_SALIDA_DOCUMENTOS', 'Salida De Documentos', 'OBJETO', '/caja/procesos/custodia/salida-documentos', 'salida-de-documentos', 'output', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_ANULA_DOCUMENTO_CUSTODIA', 'Anula Documento En Custodia', 'OBJETO', '/caja/procesos/custodia/anula-documento-custodia', 'anula-documento-en-custodia', 'folder_off', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_ACTUALIZACION_VALOR_DOCUMENTOS', 'Actualizacion Valor De Documentos', 'OBJETO', '/caja/procesos/custodia/actualizacion-valor-documentos', 'actualizacion-valor-de-documentos', 'currency_exchange', 6);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_PROCESOS_CUSTODIA_MANTENIMIENTO_UNIDAD_INTERNA', 'Mantenimiento Unidad Interna', 'OBJETO', '/caja/procesos/custodia/mantenimiento-unidad-interna', 'mantenimiento-unidad-interna', 'home_repair_service', 7);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES', 'Comprobantes', 'OBJETO', '/caja/consultas/comprobantes', 'comprobantes', 'receipt', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_DE_INGRESO_CAJA', 'De Ingreso A Caja', 'OBJETO', '/caja/consultas/comprobantes/de-ingreso-caja', 'de-ingreso-a-caja', 'login', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_POR_DIA', 'Por Dia', 'OBJETO', '/caja/consultas/comprobantes/por-dia', 'por-dia', 'today', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_POR_CONTABILIDAD', 'Por Contabilidad', 'OBJETO', '/caja/consultas/comprobantes/por-contabilidad', 'por-contabilidad', 'account_balance', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_POR_CAJA_RECAUDADORA', 'Por Caja Recaudadora', 'OBJETO', '/caja/consultas/comprobantes/por-caja-recaudadora', 'por-caja-recaudadora', 'point_of_sale', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_ANULADOS', 'Anulados', 'OBJETO', '/caja/consultas/comprobantes/anulados', 'anulados', 'block', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_RELACION_ENTREGA_VALORES_DEPOSITO', 'Relacion De Entrega Valores A Deposito', 'OBJETO', '/caja/consultas/comprobantes/relacion-entrega-valores-deposito', 'relacion-de-entrega-valores-a-deposito', 'list_alt', 6);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_COMPROBANTES_TRAZABILIDAD_COMPROBANTES_INGRESO', 'Trazabilidad Comprobantes De Ingreso', 'OBJETO', '/caja/consultas/comprobantes/trazabilidad-comprobantes-ingreso', 'trazabilidad-comprobantes-de-ingreso', 'route', 7);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_DEPOSITOS', 'Depositos', 'OBJETO', '/caja/consultas/depositos', 'depositos', 'savings', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_DEPOSITOS_DIARIOS', 'Diarios', 'OBJETO', '/caja/consultas/depositos/diarios', 'diarios', 'calendar_month', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_DEPOSITOS_PENDIENTES', 'Pendientes', 'OBJETO', '/caja/consultas/depositos/pendientes', 'pendientes', 'pending', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES', 'Cheques', 'OBJETO', '/caja/consultas/cheques', 'cheques', 'price_check', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_EN_CAJA', 'En Caja', 'OBJETO', '/caja/consultas/cheques/en-caja', 'en-caja', 'inbox', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_EN_CAJA_POR_CONTABILIDAD', 'En Caja Por Contabilidad', 'OBJETO', '/caja/consultas/cheques/en-caja-por-contabilidad', 'en-caja-por-contabilidad', 'account_balance', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_ENTREGADOS', 'Entregados', 'OBJETO', '/caja/consultas/cheques/entregados', 'entregados', 'outbox', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_POR_NOMBRE', 'Por Nombre', 'OBJETO', '/caja/consultas/cheques/por-nombre', 'por-nombre', 'sort_by_alpha', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_POR_RUT', 'Por Rut', 'OBJETO', '/caja/consultas/cheques/por-rut', 'por-rut', 'badge', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_POR_TRANSFER', 'Por Transfer', 'OBJETO', '/caja/consultas/cheques/por-transfer', 'por-transfer', 'sync_alt', 6);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_POR_CADUCAR', 'Por Caducar', 'OBJETO', '/caja/consultas/cheques/por-caducar', 'por-caducar', 'timer', 7);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CHEQUES_CADUCADOS', 'Caducados', 'OBJETO', '/caja/consultas/cheques/caducados', 'caducados', 'timer_off', 8);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CUSTODIA', 'Custodia', 'OBJETO', '/caja/consultas/custodia', 'custodia', 'lock', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CUSTODIA_DOCUMENTOS_CUSTODIA', 'Documentos En Custodia', 'OBJETO', '/caja/consultas/custodia/documentos-custodia', 'documentos-en-custodia', 'folder_special', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CUSTODIA_DOCUMENTOS_CUSTODIA_VENCIDOS', 'Documentos En Custodia Vencidos', 'OBJETO', '/caja/consultas/custodia/documentos-custodia-vencidos', 'documentos-en-custodia-vencidos', 'event_busy', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CUSTODIA_DOCUMENTOS_CUSTODIA_POR_VENCER', 'Documentos En Custodia Por Vencer', 'OBJETO', '/caja/consultas/custodia/documentos-custodia-por-vencer', 'documentos-en-custodia-por-vencer', 'alarm', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_CONSULTAS_CUSTODIA_DOCUMENTOS_ENTREGADOS_CUSTODIA', 'Documentos Entregados De Custodia', 'OBJETO', '/caja/consultas/custodia/documentos-entregados-custodia', 'documentos-entregados-de-custodia', 'assignment_return', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_ARQUEO_DIARIO', 'Arqueo Diario', 'OBJETO', '/caja/informes/arqueo-diario', 'arqueo-diario', 'fact_check', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES', 'Comprobantes', 'OBJETO', '/caja/informes/comprobantes', 'comprobantes', 'summarize', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_DE_INGRESO_CAJA', 'De Ingreso A Caja', 'OBJETO', '/caja/informes/comprobantes/de-ingreso-caja', 'de-ingreso-a-caja', 'login', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_DE_INGRESO_BANCO', 'De Ingreso A Banco', 'OBJETO', '/caja/informes/comprobantes/de-ingreso-banco', 'de-ingreso-a-banco', 'account_balance', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_POR_DIA', 'Por Dia', 'OBJETO', '/caja/informes/comprobantes/por-dia', 'por-dia', 'today', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_POR_CONTABILIDAD', 'Por Contabilidad', 'OBJETO', '/caja/informes/comprobantes/por-contabilidad', 'por-contabilidad', 'account_balance', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_POR_UNIDAD_INTERNA', 'Por Unidad Interna', 'OBJETO', '/caja/informes/comprobantes/por-unidad-interna', 'por-unidad-interna', 'business', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_POR_VENTA_CREDITO', 'Por Venta Credito', 'OBJETO', '/caja/informes/comprobantes/por-venta-credito', 'por-venta-credito', 'credit_score', 6);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_ANULADOS', 'Anulados', 'OBJETO', '/caja/informes/comprobantes/anulados', 'anulados', 'block', 7);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_POR_CAJA_RECAUDADORA', 'Por Caja Recaudadora', 'OBJETO', '/caja/informes/comprobantes/por-caja-recaudadora', 'por-caja-recaudadora', 'point_of_sale', 8);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_DETALLE_POR_DIA', 'Detalle Por Dia', 'OBJETO', '/caja/informes/comprobantes/detalle-por-dia', 'detalle-por-dia', 'calendar_view_day', 9);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_COMPROBANTES_RELACION_ENTREGA_VALORES_DEPOSITO', 'Relacion De Entrega Valores A Deposito', 'OBJETO', '/caja/informes/comprobantes/relacion-entrega-valores-deposito', 'relacion-de-entrega-valores-a-deposito', 'list_alt', 10);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_DEPOSITOS', 'Depositos', 'OBJETO', '/caja/informes/depositos', 'depositos', 'savings', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_DEPOSITOS_DEPOSITOS_DIARIOS', 'Depositos Diarios', 'OBJETO', '/caja/informes/depositos/depositos-diarios', 'depositos-diarios', 'event_note', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_DEPOSITOS_INGRESOS_POR_DEPOSITAR', 'Ingresos Por Depositar', 'OBJETO', '/caja/informes/depositos/ingresos-por-depositar', 'ingresos-por-depositar', 'schedule_send', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CHEQUES', 'Cheques', 'OBJETO', '/caja/informes/cheques', 'cheques', 'price_check', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CHEQUES_EN_CAJA', 'En Caja', 'OBJETO', '/caja/informes/cheques/en-caja', 'en-caja', 'inbox', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CHEQUES_EN_CAJA_POR_CONTABILIDAD', 'En Caja Por Contabilidad', 'OBJETO', '/caja/informes/cheques/en-caja-por-contabilidad', 'en-caja-por-contabilidad', 'account_balance', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CHEQUES_ENTREGADOS', 'Entregados', 'OBJETO', '/caja/informes/cheques/entregados', 'entregados', 'outbox', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CHEQUES_CADUCADOS', 'Caducados', 'OBJETO', '/caja/informes/cheques/caducados', 'caducados', 'timer_off', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA', 'Custodia', 'OBJETO', '/caja/informes/custodia', 'custodia', 'security', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_DOCUMENTOS_CUSTODIA', 'Documentos En Custodia', 'OBJETO', '/caja/informes/custodia/documentos-custodia', 'documentos-en-custodia', 'folder_special', 1);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_DOCUMENTOS_CUSTODIA_VENCIDOS', 'Documentos En Custodia Vencidos', 'OBJETO', '/caja/informes/custodia/documentos-custodia-vencidos', 'documentos-en-custodia-vencidos', 'event_busy', 2);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_DOCUMENTOS_CUSTODIA_POR_VENCER', 'Documentos En Custodia Por Vencer', 'OBJETO', '/caja/informes/custodia/documentos-custodia-por-vencer', 'documentos-en-custodia-por-vencer', 'alarm', 3);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_DOCUMENTOS_ENTREGADOS_CUSTODIA', 'Documentos Entregados De Custodia', 'OBJETO', '/caja/informes/custodia/documentos-entregados-custodia', 'documentos-entregados-de-custodia', 'assignment_return', 4);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_DOCUMENTOS_VIGENTES', 'Documentos Vigentes', 'OBJETO', '/caja/informes/custodia/documentos-vigentes', 'documentos-vigentes', 'check_circle', 5);
    pkg_seguridad_admin.p_upsert_nodo('CAJA_INFORMES_CUSTODIA_REIMPRESION_COMPROBANTES_CUSTODIA', 'Reimpresion Comprobantes De Custodia', 'OBJETO', '/caja/informes/custodia/reimpresion-comprobantes-custodia', 'reimpresion-comprobantes-de-custodia', 'print', 6);
    COMMIT;
END;


/
