-- ==========================================
-- POSTGRESQL TRIGGERS & FUNCTIONS
-- ==========================================

SET search_path TO ngac, public;

-- 1. AUDIT FIELD TRIGGER FUNCTION

CREATE OR REPLACE FUNCTION fn_update_audit_fields()
RETURNS TRIGGER AS $$
BEGIN
    NEW.FECHA_MODIFICACION := CURRENT_TIMESTAMP;
    NEW.MODIFICADO_POR := CURRENT_USER;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Bind audit trigger to audited tables
CREATE TRIGGER TRG_ACC_NODOS_AUDIT
    BEFORE UPDATE ON ACC_NODOS
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_ASIGNACIONES_AUDIT
    BEFORE UPDATE ON ACC_ASIGNACIONES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_ASOCIACIONES_AUDIT
    BEFORE UPDATE ON ACC_ASOCIACIONES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_PROHIBICIONES_AUDIT
    BEFORE UPDATE ON ACC_PROHIBICIONES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_OPERACIONES_AUDIT
    BEFORE UPDATE ON ACC_OPERACIONES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_TIPOS_NODO_AUDIT
    BEFORE UPDATE ON ACC_TIPOS_NODO
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_ACC_ROLES_AUDIT
    BEFORE UPDATE ON ACC_ROLES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_SAFI_ENTIDADES_AUDIT
    BEFORE UPDATE ON SAFI_ENTIDADES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_SAFI_UNIDADES_AUDIT
    BEFORE UPDATE ON SAFI_UNIDADES
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();

CREATE TRIGGER TRG_SAFI_USUARIOS_AUDIT
    BEFORE UPDATE ON SAFI_USUARIOS
    FOR EACH ROW EXECUTE FUNCTION fn_update_audit_fields();


-- 2. SOFT DELETE TRIGGER FUNCTION

CREATE OR REPLACE FUNCTION fn_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.ACTIVO = 'N' AND OLD.ACTIVO = 'S' THEN
        NEW.FECHA_ELIMINACION := CURRENT_TIMESTAMP;
        NEW.ELIMINADO_POR := CURRENT_USER;
    ELSIF NEW.ACTIVO = 'S' AND OLD.ACTIVO = 'N' THEN
        NEW.FECHA_ELIMINACION := NULL;
        NEW.ELIMINADO_POR := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Bind soft delete trigger to SAFI tables
CREATE TRIGGER TRG_SAFI_ENTIDADES_SD
    BEFORE UPDATE ON SAFI_ENTIDADES
    FOR EACH ROW EXECUTE FUNCTION fn_soft_delete();

CREATE TRIGGER TRG_SAFI_UNIDADES_SD
    BEFORE UPDATE ON SAFI_UNIDADES
    FOR EACH ROW EXECUTE FUNCTION fn_soft_delete();

CREATE TRIGGER TRG_SAFI_USUARIOS_SD
    BEFORE UPDATE ON SAFI_USUARIOS
    FOR EACH ROW EXECUTE FUNCTION fn_soft_delete();


-- 3. NODE-MENU SYNCHRONIZATION FUNCTION AND TRIGGER

CREATE OR REPLACE FUNCTION fn_sync_menu_nodos()
RETURNS TRIGGER AS $$
DECLARE
    v_tipo VARCHAR(50);
BEGIN
    -- Get code of the node type
    SELECT CODIGO_TIPO INTO v_tipo
    FROM ACC_TIPOS_NODO
    WHERE ID_TIPO_NODO = NEW.ID_TIPO_NODO;
    
    -- Sync if it is visual resource
    IF v_tipo IN ('OBJ_ATTR', 'OBJETO', 'OA', 'CARPETA') THEN
        IF TG_OP = 'INSERT' THEN
            INSERT INTO ACC_MENU_NODOS (
                ID_NODO, ETIQUETA_VISIBLE, URL_RUTA_VISIBLE, SLUG_VISIBLE,
                ICONO_VISIBLE, DESCRIPCION_VISIBLE, ORDEN_VISUAL, ACTIVO, CREADO_POR, FECHA_CREACION
            ) VALUES (
                NEW.ID_NODO, NEW.ETIQUETA, NEW.URL_RUTA, NEW.SLUG,
                NEW.ICONO, NEW.DESCRIPCION, NEW.ORDEN_VISUAL, NEW.ACTIVO, NEW.CREADO_POR, NEW.FECHA_CREACION
            );
        ELSIF TG_OP = 'UPDATE' THEN
            UPDATE ACC_MENU_NODOS
            SET ETIQUETA_VISIBLE = NEW.ETIQUETA,
                URL_RUTA_VISIBLE = NEW.URL_RUTA,
                slug_visible = NEW.SLUG,
                ICONO_VISIBLE = NEW.ICONO,
                DESCRIPCION_VISIBLE = NEW.DESCRIPCION,
                ORDEN_VISUAL = NEW.ORDEN_VISUAL,
                ACTIVO = NEW.ACTIVO,
                MODIFICADO_POR = NEW.MODIFICADO_POR,
                FECHA_MODIFICACION = NEW.FECHA_MODIFICACION
            WHERE ID_NODO = NEW.ID_NODO;
        END IF;
    END IF;
    RETURN NEW;
EXCEPTION
    WHEN OTHERS THEN
        INSERT INTO ACC_LOG_ERRORES (MODULO, MENSAJE, FECHA)
        VALUES ('TRIG_SYNC_MENU', 'Error al sincronizar nodo ID: ' || COALESCE(NEW.ID_NODO::text, 'NULL') || ' - ' || SQLERRM, CURRENT_TIMESTAMP);
        RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Bind AFTER INSERT OR UPDATE trigger
CREATE TRIGGER TRG_ACC_NODOS_SYNC_MENU
    AFTER INSERT OR UPDATE ON ACC_NODOS
    FOR EACH ROW EXECUTE FUNCTION fn_sync_menu_nodos();
