BEGIN
    pkg_seguridad_admin.p_upsert_nodo('ROL_ADMVO', 'ROL_ADMVO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_ANALI', 'ROL_ANALI', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_AUDIT', 'ROL_AUDIT', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_JEFE_ABAT', 'ROL_JEFE_ABAT', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_JEFE_ADQ', 'ROL_JEFE_ADQ', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_JEFE_CONT', 'ROL_JEFE_CONT', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_JEFE_FIN', 'ROL_JEFE_FIN', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_JEFE', 'ROL_JEFE', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_SUPER', 'ROL_SUPER', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_CONSOLI', 'ROL_CONSOLI', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_COMP', 'ROL_COMP', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_LOGIS', 'ROL_LOGIS', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_ACTA', 'ROL_ACTA', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_DIGITADOR', 'ROL_DIGITADOR', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_OPER', 'ROL_OPER', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_AYU', 'ROL_AYU', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_PERSONAL', 'ROL_PERSONAL', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_RRHH', 'ROL_RRHH', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_CONTA', 'ROL_CONTA', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_CDTE', 'ROL_CDTE', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_DIRFIN', 'ROL_DIRFIN', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_DAF', 'ROL_DAF', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_AGREGADURIA', 'ROL_AGREGADURIA', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_BODEGUERO', 'ROL_BODEGUERO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_CONSULTOR', 'ROL_CONSULTOR', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_CONTRATO', 'ROL_CONTRATO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_DIVEDU', 'ROL_DIVEDU', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_FLUJOCAJA', 'ROL_FLUJOCAJA', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_GESTION', 'ROL_GESTION', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_MAW', 'ROL_MAW', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_MAYORDOMO', 'ROL_MAYORDOMO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_MEMO', 'ROL_MEMO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_NUTRI', 'ROL_NUTRI', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_PRESUPUESTO', 'ROL_PRESUPUESTO', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_SIAPER', 'ROL_SIAPER', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_UI', 'ROL_UI', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('USU_CF', 'USU_CF', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('USU_ENTE', 'USU_ENTE', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_SYSADMIN', 'ROL_SYSADMIN', 'USR_ATTR', NULL, NULL, 'groups', 0);
    pkg_seguridad_admin.p_upsert_nodo('ROL_DEV', 'ROL_DEV', 'USR_ATTR', NULL, NULL, 'groups', 0);
    COMMIT;
END;
/
