SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `ACC_ASIGNACIONES` (
    `ID_ASIGNACION` BIGINT AUTO_INCREMENT,
    `ID_PADRE` BIGINT,
    `ID_HIJO` BIGINT,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_ASIGNACIONES PRIMARY KEY (`ID_ASIGNACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_ASOCIACIONES` (
    `ID_ASOCIACION` BIGINT AUTO_INCREMENT,
    `ID_USR_ATTR` BIGINT,
    `ID_OBJ_ATTR` BIGINT,
    `ID_OP` BIGINT,
    `CONDICION_JSON` VARCHAR(2000),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_ASOCIACIONES PRIMARY KEY (`ID_ASOCIACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_LOG_ACCESOS` (
    `ID_LOG` BIGINT AUTO_INCREMENT,
    `USUARIO` VARCHAR(50),
    `CODIGO_OBJETO` VARCHAR(100),
    `OPERACIONES` VARCHAR(256),
    `AUTORIZADO` TINYINT(1),
    `JSON_CONTEXTO` LONGTEXT,
    `FECHA_REGISTRO` DATETIME(6) DEFAULT CURRENT_DATETIME(6),
    CONSTRAINT PK_ACC_LOG_ACCESOS PRIMARY KEY (`ID_LOG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_LOG_ERRORES` (
    `ID_LOG` BIGINT,
    `FECHA` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `MODULO` VARCHAR(100),
    `MENSAJE` VARCHAR(4000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_MENU_ASIGNACIONES` (
    `ID_MENU_ASIGNACION` BIGINT AUTO_INCREMENT,
    `ID_MENU_PADRE` BIGINT,
    `ID_MENU_HIJO` BIGINT,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_MENU_ASIGNACIONES PRIMARY KEY (`ID_MENU_ASIGNACION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_MENU_NODOS` (
    `ID_MENU_NODO` BIGINT AUTO_INCREMENT,
    `ID_NODO` BIGINT,
    `ETIQUETA_VISIBLE` VARCHAR(500),
    `URL_RUTA_VISIBLE` VARCHAR(1000),
    `SLUG_VISIBLE` VARCHAR(500),
    `ICONO_VISIBLE` VARCHAR(100),
    `DESCRIPCION_VISIBLE` VARCHAR(1000),
    `ORDEN_VISUAL` BIGINT DEFAULT 0,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_MENU_NODOS PRIMARY KEY (`ID_MENU_NODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_NODOS` (
    `ID_NODO` BIGINT AUTO_INCREMENT,
    `ID_TIPO_NODO` BIGINT,
    `CODIGO_TECNICO` VARCHAR(255),
    `ETIQUETA` VARCHAR(500),
    `URL_RUTA` VARCHAR(1000),
    `SLUG` VARCHAR(500),
    `ICONO` VARCHAR(100),
    `ORDEN_VISUAL` BIGINT DEFAULT 0,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `DESCRIPCION` VARCHAR(1000),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_NODOS PRIMARY KEY (`ID_NODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_OPERACIONES` (
    `ID_OP` BIGINT AUTO_INCREMENT,
    `NOMBRE_OP` VARCHAR(100),
    `DESCRIPCION` VARCHAR(255),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_OPERACIONES PRIMARY KEY (`ID_OP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_POLICY_MENU_RAICES` (
    `ID_POLICY_MENU_RAIZ` BIGINT AUTO_INCREMENT,
    `ID_POLICY` BIGINT,
    `ID_MENU_NODO` BIGINT,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_POLICY_MENU_RAICES PRIMARY KEY (`ID_POLICY_MENU_RAIZ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_PROHIBICIONES` (
    `ID_PROHIBICION` BIGINT AUTO_INCREMENT,
    `ID_USR_ATTR` BIGINT,
    `ID_OBJ_ATTR` BIGINT,
    `ID_OP` BIGINT,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_PROHIBICIONES PRIMARY KEY (`ID_PROHIBICION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_ROLES` (
    `ID_ROL` BIGINT AUTO_INCREMENT,
    `CODIGO` VARCHAR(50),
    `NOMBRE` VARCHAR(100),
    `DESCRIPCION` VARCHAR(255),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_ROLES PRIMARY KEY (`ID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ACC_TIPOS_NODO` (
    `ID_TIPO_NODO` BIGINT AUTO_INCREMENT,
    `CODIGO_TIPO` VARCHAR(50),
    `DESCRIPCION` VARCHAR(255),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_ACC_TIPOS_NODO PRIMARY KEY (`ID_TIPO_NODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_ENTIDADES` (
    `ID_ENTIDAD` BIGINT AUTO_INCREMENT,
    `SLUG_ENTIDAD` VARCHAR(4000),
    `NOMBRE_ENTIDAD` VARCHAR(255),
    `TIPO_ENTIDAD` VARCHAR(50),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `CODIGO` VARCHAR(100),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_ENTIDADES PRIMARY KEY (`ID_ENTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_MODULO_NODOS` (
    `ID_MODULO_NODO` BIGINT AUTO_INCREMENT,
    `ID_MODULO` BIGINT,
    `ID_NODO` BIGINT,
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_MODULO_NODOS PRIMARY KEY (`ID_MODULO_NODO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_MODULOS` (
    `ID_MODULO` BIGINT AUTO_INCREMENT,
    `CODIGO` VARCHAR(100),
    `NOMBRE` VARCHAR(255),
    `DESCRIPCION` VARCHAR(1000),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `CREADO_POR` VARCHAR(100) DEFAULT 'SYSTEM',
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_MODULOS PRIMARY KEY (`ID_MODULO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_UNIDADES` (
    `ID_UNIDAD` BIGINT AUTO_INCREMENT,
    `SLUG_UNIDAD` VARCHAR(4000),
    `NOMBRE_UNIDAD` VARCHAR(255),
    `DESCRIPCION` VARCHAR(500),
    `ACTIVO` VARCHAR(1) DEFAULT 'S',
    `CODIGO` VARCHAR(100),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_UNIDADES PRIMARY KEY (`ID_UNIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_UNIDADES_ENTIDADES` (
    `ID_UNIDAD` BIGINT,
    `ID_ENTIDAD` BIGINT,
    `ACTIVO` VARCHAR(1),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_UNIDADES_ENTIDADES PRIMARY KEY (`ID_UNIDAD`, `ID_ENTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_USUARIOS` (
    `ID_USUARIO` BIGINT AUTO_INCREMENT,
    `SLUG_USUARIO` VARCHAR(100),
    `RUT` BIGINT,
    `DV` VARCHAR(1),
    `NOMBRES` VARCHAR(100),
    `APELLIDOS` VARCHAR(100),
    `EMAIL` VARCHAR(150),
    `ACTIVO` VARCHAR(1),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_USUARIOS PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_USUARIOS_ENTIDADES` (
    `ID_USUARIO` BIGINT,
    `ID_ENTIDAD` BIGINT,
    `ACTIVO` VARCHAR(1),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_USUARIOS_ENTIDADES PRIMARY KEY (`ID_USUARIO`, `ID_ENTIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SAFI_USUARIOS_UNIDADES` (
    `ID_USUARIO` BIGINT,
    `ID_UNIDAD` BIGINT,
    `ACTIVO` VARCHAR(1),
    `FECHA_CREACION` DATETIME,
    `CREADO_POR` VARCHAR(100),
    `FECHA_MODIFICACION` DATETIME,
    `MODIFICADO_POR` VARCHAR(100),
    `FECHA_ELIMINACION` DATETIME,
    `ELIMINADO_POR` VARCHAR(100),
    CONSTRAINT PK_SAFI_USUARIOS_UNIDADES PRIMARY KEY (`ID_USUARIO`, `ID_UNIDAD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Unique Constraints



-- Foreign Keys



SET FOREIGN_KEY_CHECKS = 1;


-- Indexes

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX IDX_ACC_MENU_ASIG_HIJO ON ACC_MENU_ASIGNACIONES (ID_MENU_HIJO)
;

CREATE INDEX IDX_ACC_MENU_ASIG_PADRE ON ACC_MENU_ASIGNACIONES (ID_MENU_PADRE)
;

CREATE INDEX IDX_ACC_MENU_NODOS_NODO ON ACC_MENU_NODOS (ID_NODO)
;

CREATE INDEX IDX_ACC_POL_MENU_POLICY ON ACC_POLICY_MENU_RAICES (ID_POLICY)
;

CREATE INDEX IDX_ACC_POL_MENU_RAIZ ON ACC_POLICY_MENU_RAICES (ID_MENU_NODO)
;

CREATE INDEX IDX_ASIG_HIJO ON ACC_ASIGNACIONES (ID_HIJO, ID_PADRE)
;

CREATE INDEX IDX_ASOCIACIONES_OBJ ON ACC_ASOCIACIONES (ID_OBJ_ATTR)
;

CREATE INDEX IDX_ASOCIACIONES_OP ON ACC_ASOCIACIONES (ID_OP)
;

CREATE INDEX IDX_ASOCIACIONES_USR ON ACC_ASOCIACIONES (ID_USR_ATTR)
;

CREATE INDEX IDX_ASOCIACIONES_USR_OBJ ON ACC_ASOCIACIONES (ID_USR_ATTR, ID_OBJ_ATTR)
;

CREATE INDEX IDX_LOG_ACCESOS_FECHA ON ACC_LOG_ACCESOS (FECHA_REGISTRO)
;

CREATE INDEX IDX_LOG_ACCESOS_OBJ ON ACC_LOG_ACCESOS (CODIGO_OBJETO)
;

CREATE INDEX IDX_LOG_ACCESOS_USR ON ACC_LOG_ACCESOS (USUARIO)
;

CREATE INDEX IDX_LOG_ERRORES_FECHA ON ACC_LOG_ERRORES (FECHA)
;

CREATE INDEX IDX_LOG_ERRORES_FECHA_MODULO ON ACC_LOG_ERRORES (FECHA, MODULO)
;

CREATE INDEX IDX_LOG_ERRORES_MODULO ON ACC_LOG_ERRORES (MODULO)
;

CREATE INDEX IDX_NODOS_TIPO ON ACC_NODOS (ID_TIPO_NODO, ACTIVO)
;

CREATE INDEX IDX_SAFI_UNIENT_ENT ON SAFI_UNIDADES_ENTIDADES (ID_ENTIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_UNIENT_UNI ON SAFI_UNIDADES_ENTIDADES (ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_USUENT_ENT ON SAFI_USUARIOS_ENTIDADES (ID_ENTIDAD)
;

CREATE INDEX IDX_SAFI_USUENT_USU ON SAFI_USUARIOS_ENTIDADES (ID_USUARIO)
;

CREATE INDEX IDX_SAFI_USUUNI_UNI ON SAFI_USUARIOS_UNIDADES (ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_USUUNI_USU ON SAFI_USUARIOS_UNIDADES (ID_USUARIO)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX PK_ACC_ASIGNACIONES ON ACC_ASIGNACIONES (ID_ASIGNACION)
;

CREATE UNIQUE INDEX PK_ACC_ASOCIACIONES ON ACC_ASOCIACIONES (ID_ASOCIACION)
;

CREATE UNIQUE INDEX PK_ACC_LOG_ACCESOS ON ACC_LOG_ACCESOS (ID_LOG)
;

CREATE UNIQUE INDEX PK_ACC_MENU_ASIGNACIONES ON ACC_MENU_ASIGNACIONES (ID_MENU_ASIGNACION)
;

CREATE UNIQUE INDEX PK_ACC_MENU_NODOS ON ACC_MENU_NODOS (ID_MENU_NODO)
;

CREATE UNIQUE INDEX PK_ACC_NODOS ON ACC_NODOS (ID_NODO)
;

CREATE UNIQUE INDEX PK_ACC_OPERACIONES ON ACC_OPERACIONES (ID_OP)
;

CREATE UNIQUE INDEX PK_ACC_POLICY_MENU_RAICES ON ACC_POLICY_MENU_RAICES (ID_POLICY_MENU_RAIZ)
;

CREATE UNIQUE INDEX PK_ACC_PROHIBICIONES ON ACC_PROHIBICIONES (ID_PROHIBICION)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX PK_ACC_ROLES ON ACC_ROLES (ID_ROL)
;

CREATE UNIQUE INDEX PK_ACC_TIPOS_NODO ON ACC_TIPOS_NODO (ID_TIPO_NODO)
;

CREATE UNIQUE INDEX PK_SAFI_UNI_ENT ON SAFI_UNIDADES_ENTIDADES (ID_UNIDAD, ID_ENTIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX PK_SAFI_USU_ENT ON SAFI_USUARIOS_ENTIDADES (ID_USUARIO, ID_ENTIDAD)
;

CREATE UNIQUE INDEX PK_SAFI_USU_UNI ON SAFI_USUARIOS_UNIDADES (ID_USUARIO, ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX SAFI_MODULO_NODOS_PK ON SAFI_MODULO_NODOS (ID_MODULO_NODO)
;

CREATE UNIQUE INDEX SAFI_MODULO_NODOS_UK ON SAFI_MODULO_NODOS (ID_MODULO, ID_NODO)
;

CREATE UNIQUE INDEX SAFI_MODULOS_CODIGO_UK ON SAFI_MODULOS (CODIGO)
;

CREATE UNIQUE INDEX SAFI_MODULOS_PK ON SAFI_MODULOS (ID_MODULO)
;

CREATE UNIQUE INDEX SYS_C008582 ON ACC_LOG_ERRORES (ID_LOG)
;

CREATE UNIQUE INDEX SYS_C008630 ON SAFI_USUARIOS (SLUG_USUARIO)
;

CREATE UNIQUE INDEX SYS_C008631 ON SAFI_USUARIOS (RUT)
;

CREATE UNIQUE INDEX SYS_C008635 ON SAFI_UNIDADES (ID_UNIDAD)
;

CREATE UNIQUE INDEX SYS_C008636 ON SAFI_UNIDADES (SLUG_UNIDAD)
;

CREATE UNIQUE INDEX SYS_C008640 ON SAFI_ENTIDADES (ID_ENTIDAD)
;

CREATE UNIQUE INDEX SYS_C008641 ON SAFI_ENTIDADES (SLUG_ENTIDAD)
;

CREATE UNIQUE INDEX SYS_C008699 ON SAFI_USUARIOS (ID_USUARIO)
;

CREATE UNIQUE INDEX UQ_ACC_ASIGN_REL ON ACC_ASIGNACIONES (ID_PADRE, ID_HIJO)
;

CREATE UNIQUE INDEX UQ_ACC_ASOC_REL ON ACC_ASOCIACIONES (ID_USR_ATTR, ID_OBJ_ATTR, ID_OP)
;

CREATE UNIQUE INDEX UQ_ACC_MENU_ASIG_REL ON ACC_MENU_ASIGNACIONES (ID_MENU_PADRE, ID_MENU_HIJO)
;

CREATE UNIQUE INDEX UQ_ACC_NODOS_COD ON ACC_NODOS (CODIGO_TECNICO)
;

CREATE UNIQUE INDEX UQ_ACC_OPERACIONES_NOM ON ACC_OPERACIONES (NOMBRE_OP)
;

CREATE UNIQUE INDEX UQ_ACC_POL_MENU_REL ON ACC_POLICY_MENU_RAICES (ID_POLICY, ID_MENU_NODO)
;

CREATE UNIQUE INDEX UQ_ACC_PROH_REL ON ACC_PROHIBICIONES (ID_USR_ATTR, ID_OBJ_ATTR, ID_OP)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX UQ_ACC_ROLES ON ACC_ROLES (CODIGO)
;

CREATE UNIQUE INDEX UQ_ACC_TIPOS_CODIGO ON ACC_TIPOS_NODO (CODIGO_TIPO)
;

CREATE UNIQUE INDEX PK_ACC_ASIGNACIONES ON ACC_ASIGNACIONES (ID_ASIGNACION)
;

CREATE UNIQUE INDEX UQ_ACC_ASIGN_REL ON ACC_ASIGNACIONES (ID_PADRE, ID_HIJO)
;

CREATE INDEX IDX_ASIG_HIJO ON ACC_ASIGNACIONES (ID_HIJO, ID_PADRE)
;

CREATE UNIQUE INDEX PK_ACC_ASOCIACIONES ON ACC_ASOCIACIONES (ID_ASOCIACION)
;

CREATE UNIQUE INDEX UQ_ACC_ASOC_REL ON ACC_ASOCIACIONES (ID_USR_ATTR, ID_OBJ_ATTR, ID_OP)
;

CREATE INDEX IDX_ASOCIACIONES_USR ON ACC_ASOCIACIONES (ID_USR_ATTR)
;

CREATE INDEX IDX_ASOCIACIONES_OBJ ON ACC_ASOCIACIONES (ID_OBJ_ATTR)
;

CREATE INDEX IDX_ASOCIACIONES_OP ON ACC_ASOCIACIONES (ID_OP)
;

CREATE INDEX IDX_ASOCIACIONES_USR_OBJ ON ACC_ASOCIACIONES (ID_USR_ATTR, ID_OBJ_ATTR)
;

CREATE UNIQUE INDEX PK_ACC_LOG_ACCESOS ON ACC_LOG_ACCESOS (ID_LOG)
;

CREATE INDEX IDX_LOG_ACCESOS_USR ON ACC_LOG_ACCESOS (USUARIO)
;

CREATE INDEX IDX_LOG_ACCESOS_FECHA ON ACC_LOG_ACCESOS (FECHA_REGISTRO)
;

CREATE INDEX IDX_LOG_ACCESOS_OBJ ON ACC_LOG_ACCESOS (CODIGO_OBJETO)
;

CREATE INDEX IDX_LOG_ERRORES_MODULO ON ACC_LOG_ERRORES (MODULO)
;

CREATE UNIQUE INDEX SYS_C008582 ON ACC_LOG_ERRORES (ID_LOG)
;

CREATE INDEX IDX_LOG_ERRORES_FECHA ON ACC_LOG_ERRORES (FECHA)
;

CREATE INDEX IDX_LOG_ERRORES_FECHA_MODULO ON ACC_LOG_ERRORES (FECHA, MODULO)
;

CREATE UNIQUE INDEX PK_ACC_MENU_ASIGNACIONES ON ACC_MENU_ASIGNACIONES (ID_MENU_ASIGNACION)
;

CREATE UNIQUE INDEX UQ_ACC_MENU_ASIG_REL ON ACC_MENU_ASIGNACIONES (ID_MENU_PADRE, ID_MENU_HIJO)
;

CREATE INDEX IDX_ACC_MENU_ASIG_PADRE ON ACC_MENU_ASIGNACIONES (ID_MENU_PADRE)
;

CREATE INDEX IDX_ACC_MENU_ASIG_HIJO ON ACC_MENU_ASIGNACIONES (ID_MENU_HIJO)
;

CREATE UNIQUE INDEX PK_ACC_MENU_NODOS ON ACC_MENU_NODOS (ID_MENU_NODO)
;

CREATE INDEX IDX_ACC_MENU_NODOS_NODO ON ACC_MENU_NODOS (ID_NODO)
;

CREATE UNIQUE INDEX PK_ACC_NODOS ON ACC_NODOS (ID_NODO)
;

CREATE UNIQUE INDEX UQ_ACC_NODOS_COD ON ACC_NODOS (CODIGO_TECNICO)
;

CREATE INDEX IDX_NODOS_TIPO ON ACC_NODOS (ID_TIPO_NODO, ACTIVO)
;

CREATE UNIQUE INDEX PK_ACC_OPERACIONES ON ACC_OPERACIONES (ID_OP)
;

CREATE UNIQUE INDEX UQ_ACC_OPERACIONES_NOM ON ACC_OPERACIONES (NOMBRE_OP)
;

CREATE UNIQUE INDEX PK_ACC_POLICY_MENU_RAICES ON ACC_POLICY_MENU_RAICES (ID_POLICY_MENU_RAIZ)
;

CREATE UNIQUE INDEX UQ_ACC_POL_MENU_REL ON ACC_POLICY_MENU_RAICES (ID_POLICY, ID_MENU_NODO)
;

CREATE INDEX IDX_ACC_POL_MENU_POLICY ON ACC_POLICY_MENU_RAICES (ID_POLICY)
;

CREATE INDEX IDX_ACC_POL_MENU_RAIZ ON ACC_POLICY_MENU_RAICES (ID_MENU_NODO)
;

CREATE UNIQUE INDEX PK_ACC_PROHIBICIONES ON ACC_PROHIBICIONES (ID_PROHIBICION)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX UQ_ACC_PROH_REL ON ACC_PROHIBICIONES (ID_USR_ATTR, ID_OBJ_ATTR, ID_OP)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX PK_ACC_ROLES ON ACC_ROLES (ID_ROL)
;

CREATE UNIQUE INDEX UQ_ACC_ROLES ON ACC_ROLES (CODIGO)
;

CREATE UNIQUE INDEX PK_ACC_TIPOS_NODO ON ACC_TIPOS_NODO (ID_TIPO_NODO)
;

CREATE UNIQUE INDEX UQ_ACC_TIPOS_CODIGO ON ACC_TIPOS_NODO (CODIGO_TIPO)
;

CREATE UNIQUE INDEX SYS_C008640 ON SAFI_ENTIDADES (ID_ENTIDAD)
;

CREATE UNIQUE INDEX SYS_C008641 ON SAFI_ENTIDADES (SLUG_ENTIDAD)
;

CREATE UNIQUE INDEX SAFI_MODULO_NODOS_PK ON SAFI_MODULO_NODOS (ID_MODULO_NODO)
;

CREATE UNIQUE INDEX SAFI_MODULO_NODOS_UK ON SAFI_MODULO_NODOS (ID_MODULO, ID_NODO)
;

CREATE UNIQUE INDEX SAFI_MODULOS_PK ON SAFI_MODULOS (ID_MODULO)
;

CREATE UNIQUE INDEX SAFI_MODULOS_CODIGO_UK ON SAFI_MODULOS (CODIGO)
;

CREATE UNIQUE INDEX SYS_C008635 ON SAFI_UNIDADES (ID_UNIDAD)
;

CREATE UNIQUE INDEX SYS_C008636 ON SAFI_UNIDADES (SLUG_UNIDAD)
;

CREATE UNIQUE INDEX PK_SAFI_UNI_ENT ON SAFI_UNIDADES_ENTIDADES (ID_UNIDAD, ID_ENTIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_UNIENT_UNI ON SAFI_UNIDADES_ENTIDADES (ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_UNIENT_ENT ON SAFI_UNIDADES_ENTIDADES (ID_ENTIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE UNIQUE INDEX SYS_C008699 ON SAFI_USUARIOS (ID_USUARIO)
;

CREATE UNIQUE INDEX SYS_C008630 ON SAFI_USUARIOS (SLUG_USUARIO)
;

CREATE UNIQUE INDEX SYS_C008631 ON SAFI_USUARIOS (RUT)
;

CREATE UNIQUE INDEX PK_SAFI_USU_ENT ON SAFI_USUARIOS_ENTIDADES (ID_USUARIO, ID_ENTIDAD)
;

CREATE INDEX IDX_SAFI_USUENT_USU ON SAFI_USUARIOS_ENTIDADES (ID_USUARIO)
;

CREATE INDEX IDX_SAFI_USUENT_ENT ON SAFI_USUARIOS_ENTIDADES (ID_ENTIDAD)
;

CREATE UNIQUE INDEX PK_SAFI_USU_UNI ON SAFI_USUARIOS_UNIDADES (ID_USUARIO, ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_USUUNI_USU ON SAFI_USUARIOS_UNIDADES (ID_USUARIO)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;

CREATE INDEX IDX_SAFI_USUUNI_UNI ON SAFI_USUARIOS_UNIDADES (ID_UNIDAD)
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
;
