-- ==========================================
-- MYSQL TRIGGERS
-- ==========================================

DELIMITER $$

-- 1. AUDITING TRIGGERS (BEFORE UPDATE)

CREATE TRIGGER TRG_ACC_NODOS_AUDIT
BEFORE UPDATE ON ACC_NODOS
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_ASIGNACIONES_AUDIT
BEFORE UPDATE ON ACC_ASIGNACIONES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_ASOCIACIONES_AUDIT
BEFORE UPDATE ON ACC_ASOCIACIONES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_PROHIBICIONES_AUDIT
BEFORE UPDATE ON ACC_PROHIBICIONES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_OPERACIONES_AUDIT
BEFORE UPDATE ON ACC_OPERACIONES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_TIPOS_NODO_AUDIT
BEFORE UPDATE ON ACC_TIPOS_NODO
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_ACC_ROLES_AUDIT
BEFORE UPDATE ON ACC_ROLES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_SAFI_ENTIDADES_AUDIT
BEFORE UPDATE ON SAFI_ENTIDADES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_SAFI_UNIDADES_AUDIT
BEFORE UPDATE ON SAFI_UNIDADES
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$

CREATE TRIGGER TRG_SAFI_USUARIOS_AUDIT
BEFORE UPDATE ON SAFI_USUARIOS
FOR EACH ROW
BEGIN
    SET NEW.FECHA_MODIFICACION = CURRENT_TIMESTAMP();
    SET NEW.MODIFICADO_POR = CURRENT_USER();
END$$


-- 2. SOFT DELETE TRIGGERS (BEFORE UPDATE)

CREATE TRIGGER TRG_SAFI_ENTIDADES_SD
BEFORE UPDATE ON SAFI_ENTIDADES
FOR EACH ROW
BEGIN
    IF NEW.ACTIVO = 'N' AND OLD.ACTIVO = 'S' THEN
        SET NEW.FECHA_ELIMINACION = CURRENT_TIMESTAMP();
        SET NEW.ELIMINADO_POR = CURRENT_USER();
    ELSEIF NEW.ACTIVO = 'S' AND OLD.ACTIVO = 'N' THEN
        SET NEW.FECHA_ELIMINACION = NULL;
        SET NEW.ELIMINADO_POR = NULL;
    END IF;
END$$

CREATE TRIGGER TRG_SAFI_UNIDADES_SD
BEFORE UPDATE ON SAFI_UNIDADES
FOR EACH ROW
BEGIN
    IF NEW.ACTIVO = 'N' AND OLD.ACTIVO = 'S' THEN
        SET NEW.FECHA_ELIMINACION = CURRENT_TIMESTAMP();
        SET NEW.ELIMINADO_POR = CURRENT_USER();
    ELSEIF NEW.ACTIVO = 'S' AND OLD.ACTIVO = 'N' THEN
        SET NEW.FECHA_ELIMINACION = NULL;
        SET NEW.ELIMINADO_POR = NULL;
    END IF;
END$$

CREATE TRIGGER TRG_SAFI_USUARIOS_SD
BEFORE UPDATE ON SAFI_USUARIOS
FOR EACH ROW
BEGIN
    IF NEW.ACTIVO = 'N' AND OLD.ACTIVO = 'S' THEN
        SET NEW.FECHA_ELIMINACION = CURRENT_TIMESTAMP();
        SET NEW.ELIMINADO_POR = CURRENT_USER();
    ELSEIF NEW.ACTIVO = 'S' AND OLD.ACTIVO = 'N' THEN
        SET NEW.FECHA_ELIMINACION = NULL;
        SET NEW.ELIMINADO_POR = NULL;
    END IF;
END$$


-- 3. NODE-MENU SYNCHRONIZATION TRIGGERS (AFTER INSERT & AFTER UPDATE)
-- In MySQL, separate triggers must be created for insert and update.

CREATE TRIGGER TRG_ACC_NODOS_SYNC_MENU_INSERT
AFTER INSERT ON ACC_NODOS
FOR EACH ROW
BEGIN
    DECLARE v_tipo VARCHAR(50);
    
    SELECT CODIGO_TIPO INTO v_tipo
    FROM ACC_TIPOS_NODO
    WHERE ID_TIPO_NODO = NEW.ID_TIPO_NODO;
    
    IF v_tipo IN ('OBJ_ATTR', 'OBJETO', 'OA', 'CARPETA') THEN
        INSERT INTO ACC_MENU_NODOS (
            ID_NODO, ETIQUETA_VISIBLE, URL_RUTA_VISIBLE, SLUG_VISIBLE,
            ICONO_VISIBLE, DESCRIPCION_VISIBLE, ORDEN_VISUAL, ACTIVO, CREADO_POR, FECHA_CREACION
        ) VALUES (
            NEW.ID_NODO, NEW.ETIQUETA, NEW.URL_RUTA, NEW.SLUG,
            NEW.ICONO, NEW.DESCRIPCION, NEW.ORDEN_VISUAL, NEW.ACTIVO, NEW.CREADO_POR, NEW.FECHA_CREACION
        );
    END IF;
END$$

CREATE TRIGGER TRG_ACC_NODOS_SYNC_MENU_UPDATE
AFTER UPDATE ON ACC_NODOS
FOR EACH ROW
BEGIN
    DECLARE v_tipo VARCHAR(50);
    
    SELECT CODIGO_TIPO INTO v_tipo
    FROM ACC_TIPOS_NODO
    WHERE ID_TIPO_NODO = NEW.ID_TIPO_NODO;
    
    IF v_tipo IN ('OBJ_ATTR', 'OBJETO', 'OA', 'CARPETA') THEN
        UPDATE ACC_MENU_NODOS
        SET ETIQUETA_VISIBLE = NEW.ETIQUETA,
            URL_RUTA_VISIBLE = NEW.URL_RUTA,
            SLUG_VISIBLE = NEW.SLUG,
            ICONO_VISIBLE = NEW.ICONO,
            DESCRIPCION_VISIBLE = NEW.DESCRIPCION,
            ORDEN_VISUAL = NEW.ORDEN_VISUAL,
            ACTIVO = NEW.ACTIVO,
            MODIFICADO_POR = NEW.MODIFICADO_POR,
            FECHA_MODIFICACION = NEW.FECHA_MODIFICACION
        WHERE ID_NODO = NEW.ID_NODO;
    END IF;
END$$

DELIMITER ;
