-- ==========================================
-- SQL SERVER TRIGGERS
-- ==========================================

-- 1. AUDITING TRIGGERS (AFTER UPDATE)
-- Using IF UPDATE(...) to prevent recursion loops.

CREATE TRIGGER TRG_ACC_NODOS_AUDIT
ON ACC_NODOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_NODOS
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_NODOS t
    INNER JOIN inserted i ON t.ID_NODO = i.ID_NODO;
END;
GO

CREATE TRIGGER TRG_ACC_ASIGNACIONES_AUDIT
ON ACC_ASIGNACIONES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_ASIGNACIONES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_ASIGNACIONES t
    INNER JOIN inserted i ON t.ID_ASIGNACION = i.ID_ASIGNACION;
END;
GO

CREATE TRIGGER TRG_ACC_ASOCIACIONES_AUDIT
ON ACC_ASOCIACIONES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_ASOCIACIONES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_ASOCIACIONES t
    INNER JOIN inserted i ON t.ID_ASOCIACION = i.ID_ASOCIACION;
END;
GO

CREATE TRIGGER TRG_ACC_PROHIBICIONES_AUDIT
ON ACC_PROHIBICIONES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_PROHIBICIONES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_PROHIBICIONES t
    INNER JOIN inserted i ON t.ID_PROHIBICION = i.ID_PROHIBICION;
END;
GO

CREATE TRIGGER TRG_ACC_OPERACIONES_AUDIT
ON ACC_OPERACIONES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_OPERACIONES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_OPERACIONES t
    INNER JOIN inserted i ON t.ID_OP = i.ID_OP;
END;
GO

CREATE TRIGGER TRG_ACC_TIPOS_NODO_AUDIT
ON ACC_TIPOS_NODO
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_TIPOS_NODO
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_TIPOS_NODO t
    INNER JOIN inserted i ON t.ID_TIPO_NODO = i.ID_TIPO_NODO;
END;
GO

CREATE TRIGGER TRG_ACC_ROLES_AUDIT
ON ACC_ROLES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) RETURN;
    
    UPDATE ACC_ROLES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM ACC_ROLES t
    INNER JOIN inserted i ON t.ID_ROL = i.ID_ROL;
END;
GO

CREATE TRIGGER TRG_SAFI_ENTIDADES_AUDIT
ON SAFI_ENTIDADES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) OR UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    UPDATE SAFI_ENTIDADES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM SAFI_ENTIDADES t
    INNER JOIN inserted i ON t.ID_ENTIDAD = i.ID_ENTIDAD;
END;
GO

CREATE TRIGGER TRG_SAFI_UNIDADES_AUDIT
ON SAFI_UNIDADES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) OR UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    UPDATE SAFI_UNIDADES
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM SAFI_UNIDADES t
    INNER JOIN inserted i ON t.ID_UNIDAD = i.ID_UNIDAD;
END;
GO

CREATE TRIGGER TRG_SAFI_USUARIOS_AUDIT
ON SAFI_USUARIOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_MODIFICACION) OR UPDATE(MODIFICADO_POR) OR UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    UPDATE SAFI_USUARIOS
    SET FECHA_MODIFICACION = GETDATE(),
        MODIFICADO_POR = SYSTEM_USER
    FROM SAFI_USUARIOS t
    INNER JOIN inserted i ON t.ID_USUARIO = i.ID_USUARIO;
END;
GO


-- 2. SOFT DELETE TRIGGERS (AFTER UPDATE ON ACTIVO COLUMN)

CREATE TRIGGER TRG_SAFI_ENTIDADES_SD
ON SAFI_ENTIDADES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    IF UPDATE(ACTIVO)
    BEGIN
        UPDATE SAFI_ENTIDADES
        SET FECHA_ELIMINACION = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN GETDATE()
                                     WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                     ELSE t.FECHA_ELIMINACION END,
            ELIMINADO_POR = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN SYSTEM_USER
                                 WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                 ELSE t.ELIMINADO_POR END
        FROM SAFI_ENTIDADES t
        INNER JOIN inserted i ON t.ID_ENTIDAD = i.ID_ENTIDAD
        INNER JOIN deleted d ON t.ID_ENTIDAD = d.ID_ENTIDAD;
    END
END;
GO

CREATE TRIGGER TRG_SAFI_UNIDADES_SD
ON SAFI_UNIDADES
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    IF UPDATE(ACTIVO)
    BEGIN
        UPDATE SAFI_UNIDADES
        SET FECHA_ELIMINACION = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN GETDATE()
                                     WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                     ELSE t.FECHA_ELIMINACION END,
            ELIMINADO_POR = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN SYSTEM_USER
                                 WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                 ELSE t.ELIMINADO_POR END
        FROM SAFI_UNIDADES t
        INNER JOIN inserted i ON t.ID_UNIDAD = i.ID_UNIDAD
        INNER JOIN deleted d ON t.ID_UNIDAD = d.ID_UNIDAD;
    END
END;
GO

CREATE TRIGGER TRG_SAFI_USUARIOS_SD
ON SAFI_USUARIOS
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF UPDATE(FECHA_ELIMINACION) OR UPDATE(ELIMINADO_POR) RETURN;
    
    IF UPDATE(ACTIVO)
    BEGIN
        UPDATE SAFI_USUARIOS
        SET FECHA_ELIMINACION = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN GETDATE()
                                     WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                     ELSE t.FECHA_ELIMINACION END,
            ELIMINADO_POR = CASE WHEN i.ACTIVO = 'N' AND d.ACTIVO = 'S' THEN SYSTEM_USER
                                 WHEN i.ACTIVO = 'S' AND d.ACTIVO = 'N' THEN NULL
                                 ELSE t.ELIMINADO_POR END
        FROM SAFI_USUARIOS t
        INNER JOIN inserted i ON t.ID_USUARIO = i.ID_USUARIO
        INNER JOIN deleted d ON t.ID_USUARIO = d.ID_USUARIO;
    END
END;
GO


-- 3. NODE-MENU SYNCHRONIZATION TRIGGER (AFTER INSERT, UPDATE ON ACC_NODOS)

CREATE TRIGGER TRG_ACC_NODOS_SYNC_MENU
ON ACC_NODOS
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    
    BEGIN TRY
        -- Insert new nodes into menu nodes if they are visual ecosystem types
        INSERT INTO ACC_MENU_NODOS (
            ID_NODO, ETIQUETA_VISIBLE, URL_RUTA_VISIBLE, SLUG_VISIBLE,
            ICONO_VISIBLE, DESCRIPCION_VISIBLE, ORDEN_VISUAL, ACTIVO, CREADO_POR, FECHA_CREACION
        )
        SELECT 
            i.ID_NODO, i.ETIQUETA, i.URL_RUTA, i.SLUG,
            i.ICONO, i.DESCRIPCION, i.ORDEN_VISUAL, i.ACTIVO, i.CREADO_POR, i.FECHA_CREACION
        FROM inserted i
        INNER JOIN ACC_TIPOS_NODO t ON i.ID_TIPO_NODO = t.ID_TIPO_NODO
        WHERE t.CODIGO_TIPO IN ('OBJ_ATTR', 'OBJETO', 'OA', 'CARPETA')
          AND NOT EXISTS (SELECT 1 FROM ACC_MENU_NODOS m WHERE m.ID_NODO = i.ID_NODO);

        -- Update existing menu nodes
        UPDATE m
        SET m.ETIQUETA_VISIBLE = i.ETIQUETA,
            m.URL_RUTA_VISIBLE = i.URL_RUTA,
            m.SLUG_VISIBLE = i.SLUG,
            m.ICONO_VISIBLE = i.ICONO,
            m.DESCRIPCION_VISIBLE = i.DESCRIPCION,
            m.ORDEN_VISUAL = i.ORDEN_VISUAL,
            m.ACTIVO = i.ACTIVO,
            m.MODIFICADO_POR = i.MODIFICADO_POR,
            m.FECHA_MODIFICACION = i.FECHA_MODIFICACION
        FROM ACC_MENU_NODOS m
        INNER JOIN inserted i ON m.ID_NODO = i.ID_NODO
        INNER JOIN ACC_TIPOS_NODO t ON i.ID_TIPO_NODO = t.ID_TIPO_NODO
        WHERE t.CODIGO_TIPO IN ('OBJ_ATTR', 'OBJETO', 'OA', 'CARPETA');

    END TRY
    BEGIN CATCH
        -- Insert error log in SQL Server
        INSERT INTO ACC_LOG_ERRORES (MODULO, MENSAJE, FECHA)
        VALUES ('TRIG_SYNC_MENU', 'Error al sincronizar nodo: ' + ERROR_MESSAGE(), GETDATE());
        THROW;
    END CATCH
END;
GO
